server:
  tomcat:
    uri-encoding: UTF-8

spring:

  mvc:
    path-match:
      matching-strategy: ant_path_matcher

  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crudpractice
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate:

      format_sql: true
      show_sql: ${SHOW_SQL}
      jdbc:
        batch_size: 200
    open-in-view: false